source 'http://rubygems.org'

#gem 'thin', '~> 1.6.2'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'slim'
gem 'httparty'
gem 'enrico'
gem 'mongo'
gem 'mongo_mapper'
gem 'bson_ext'
gem 'calendar_helper'