source 'http://rubygems.org'

#gem 'thin', '~> 1.6.2'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'slim'
gem 'httparty'
gem 'enrico'
gem 'mongo'
gem 'mongo_mapper'
gem 'bson_ext'
gem 'calendar_helper', git: 'git://github.com/nikhilnz/calendar_helper.git'
gem 'bundler'
gem 'rake'

group :test do
  gem 'webmock'
  gem 'rspec'
  gem 'rack-test'
  gem 'gherkin'
  gem 'cucumber'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
end